---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ilkertekerviptra/public_html/
    - /bin/cp -R ./index.html $DEPLOYPATH
    - /bin/cp -R ./css $DEPLOYPATH
    - /bin/cp -R ./js $DEPLOYPATH
    - /bin/cp -R ./img $DEPLOYPATH
    - /bin/cp -R ./robots.txt $DEPLOYPATH
    - /bin/cp -R ./sitemap.xml $DEPLOYPATH
